### PR TITLE
Update to Unicode 12.1.0

### PR DESCRIPTION
**Pull request by antifuchs**
reported by @wezm:

> I tried searching for the [Lobster emoji](https://unicode-table.com/en/1F99E/) and was surprised to not get a result.

### CODE REVIEW

**Comment by antifuchs** [comment]
Whoa, my tooling totally went off the rails here & converted the issue to a PR (making me the reporter), sorry for losing you the reporter status, @wezm ):

**Comment by antifuchs** [comment]
Released chars v0.4.0 (and shortly thereafter, [v0.4.1](https://crates.io/crates/chars/0.4.1)) today, featuring the lobster emojo! Thanks for the ping (-:

**Comment by wezm** [comment]
Brilliant, thank you! 🦞

**Pull request merged**
