### PR TITLE
Add data file and retrieval script for character reference names supported by HTML

### PR DESCRIPTION
**Pull request by ctsrc**
This PR relates to issue #22 and is a first step towards the request I made in that issue.

### CODE REVIEW

**Comment by ctsrc** [comment]
Note that this PR does not touch any of the source code of `chars`.

As such, the failing clippy tests are unrelated to this PR.

**Comment by antifuchs** [comment]
I am a little busy these next few days (just wrapping up an international move), so won't be able to take a good look very soon - I just wanted to say, holy CATS this is a great PR & issue that you submitted there. Thank you!!!

I'm extremely excited to get more search criteria into `chars`, and hope to be able to review & merge this soon!

**Comment by antifuchs** [comment]
For the clippy failure, I just merged a change that should make the chars_data crate tests succeed again - if you rebase, I can merge (despite what I said, I couldn't resist glancing, and it looks good) (:

**Comment by ctsrc** [comment]
> I just wanted to say, holy CATS this is a great PR & issue that you submitted there. Thank you!!!

Thanks for the kind words :)

> if you rebase, I can merge

I've rebased now. Thank you :)

**Comment by antifuchs** [comment]
Thanks so much for your contribution! As mentioned, I can take a look at integrating the data into the search/presentation functionality; or if you want to, feel free to take a stab yourself!

**Pull request merged**
