### PR TITLE
Add Homebrew install instructions

### PR DESCRIPTION
**Pull request by vladimyr**
`chars` has been added to Homebrew 🎉

### CODE REVIEW

**Comment by antifuchs** [comment]
Great news, thanks so much!

bors r+

**Comment by vladimyr** [comment]
@antifuchs Sorry to bother you but I accidentally omitted the `/formula/` URL path segment. The correct URL for the Homebrew formula is https://formulae.brew.sh/formula/chars#default Do you want me to do follow-up PR fixing it?

**Comment by antifuchs** [comment]
Oh, whoops - I should have checked that URL too. I'm happy to just commit a fix to that, thanks for letting me know (:

**Comment by vladimyr** [comment]
> Oh, whoops - I should have checked that URL too. I'm happy to just commit a fix to that, thanks for letting me know (:

Thanks for cleaning up my mess. 👍 I should've checked it in the first place but in my defense couldn't do it at the PR creation time because there is a time delay between the formula being accepted and the formula's static info page being generated.

**Comment by antifuchs** [comment]
It's all good - thanks for your contribution, I wouldn't have noticed that the formula had gone in otherwise!

**Pull request merged**
